[package]
name = "game_randomizer"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "^1"
log = "^0.4"
env_logger = "^0.9"
clap = "^2.3"
serenity = "^0.10"
tokio = { version = "1.0", features = ["macros", "signal", "rt-multi-thread"] }
